name: "01 - Building Blocks"
on: [push, workflow_dispatch]

jobs:
  echo_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello, world!"

  echo_goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: Successful step
        run: |
          echo "This step succesfully completed"
          exit 0
      - name: Say goodbye
        run: echo "Goodbye, world!"
