name: "01 - Building Blocks"
on: push

jobs:
  echo_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello, world!"

  echo_goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: Failed step
        run: |
          echo "This step will fail"
          exit 1
      - name: Say goodbye
        run: echo "Goodbye, world!"
