name: "02 - Workflow Events"
on: push
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger event
        run: echo "The event that triggered this workflow was $GITHUB_EVENT_NAME / ${{ github.event_name }}"
