name: "03 - Workflow Runners"
on:
  workflow_dispatch:
jobs:
  umbutu-echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show OS
        run: echo "This job is runnitn on ${{ runner.os }} / $RUNNER_OS"
  windows-echo:
    runs-on: windows-latest
    steps:
      - name: Show OS
        shell: bash
        run: echo "This job is runnitn on ${{ runner.os }} / $RUNNER_OS"
  macos-echo:
    runs-on: macos-latest
    steps:
      - name: Show OS
        run: echo "This job is run on ${{ runner.os }} / $RUNNER_OS"
