name: "04 - Using Actions"
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    # 0 checkout code
    # 1 install dependencies
    # 2 run tests
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: SetUp Node
        uses: actions/setup-node@v2
        with:
          node-version: "20.x"
      - name: Install Dependencies
        run: npm ci
        working-directory: 02-using-actions/my-vite-react-app
