name: "04 - Using Actions"
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 13-caching/react-app
    # 0 checkout code
    # 1 install dependencies
    # 2 run tests
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: SetUp Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Install Dependencies
        run: npm ci
  unit-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 13-caching/react-app
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: SetUp Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Install Dependencies
        run: npm ci
      - name: Run Tests
        run: npm run test
