name: 06 - Context
run-name: 06 - Context | DEBUG ${{ inputs.debug }}
on:
  push:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: false

jobs:
  echo-data:
    runs-on: ubuntu-latest
    steps:
      - name: Show the context
        run: |
          echo "Event name: $GITHUB_EVENT_NAME / ${{ github.event_name }}"
          echo "The branch that triggered this workflow was $GITHUB_REF / ${{ github.ref }}"
          echo "SHA $GITHUB_SHA / ${{ github.sha }}"
          echo "Actor: $GITHUB_ACTOR / ${{ github.actor }}"
          echo "Worflow $GITHUB_WORKFLOW / ${{ github.workflow }}"
          echo "The action that triggered this workflow was $GITHUB_ACTION / ${{ github.action }}"
          echo "The job that triggered this workflow was $GITHUB_JOB / ${{ github.job }}"
          echo "Run ID: $GITHUB_RUN_ID / ${{ github.run_id }}"
          echo "Run Number: $GITHUB_RUN_NUMBER / ${{ github.run_number }}"
      - name: Retreive variable
        run: echo "The value of the variable is ${{ vars.MY_VAR }}"
