name: 07 - Using expressions
on:
  push:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: false
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: "[debug] Print startup data"
        if: ${{ inputs.debug }}
        run: |
          echo "Trigger by event: $GITHUB_EVENT_NAME / ${{ github.event_name }}"
          echo "Branch: $GITHUB_REF / ${{ github.ref }}"
          echo "SHA: $GITHUB_SHA / ${{ github.sha }}"
          echo "Run OS: $GITHUB_ACTOR / ${{ runner.os }}"
      - name: "[debug] Print when trigger"
        if: inputs.debug && github.ref == 'refs/heads/main'
        run: echo "This is a debug run on the main branch"
      - name: Greeting
        run: echo "Hello, world!"
# how can I update an md file through pipelines?
# I have an md file with a status badge new and when
# I press a vote button in the md file I want to chance the badge to voted
# I want to do this through pipelines

