name: 09 - Using Functions
on:
  pull_request:
  workflow_dispatch:
jobs:
  echo1:
    runs-on: ubuntu-latest
    steps:
      - name: Failing step
        run: |
          echo "This is a failing step"
          exit 1
      - name: I will be skipped
        if: ${{ success() }}
        run: echo "I will print if preview step succeeds"
      - name: I will execute
        if: ${{ failure() }}
        run: echo "I will print if any preview step fails"
      - name: I will execite
        if: ${{ !cancelled() }}
        run: echo "I will always print, exccept when workflow is cancceled"
      - name: I will execute when canceled
        if: ${{ cancelled() }}
        run: echo "I will print if the workflow is canceled"
