name: 10 - Controlling and Execution flow
on:
  workflow_dispatch:
    inputs:
      pass-unit-tests:
        type: boolean
        default: false
jobs:
  lint-build:
    runs-on: ubuntu-latest
    steps:
      - name: Lint and build
        run: echo "Linting and building code"
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Running unit tests
        run: echo "Running unit tests"
      - name: Failing tests
        if: ${{ !inputs.pass-unit-tests }}
        run: exit 1
  deploy-nonprod:
    runs-on: ubuntu-latest
    needs: [lint-build, unit-tests]
    steps:
      - name: Deploy to non-prod
        run: echo "Deploying to non-prod"
  e2e-tests:
    runs-on: ubuntu-latest
    needs: deploy-nonprod
    steps:
      - name: Running E2E tests
        run: echo "Running E2E tests"
      - name: Failing tests
        if: ${{ !inputs.pass-unit-tests }}
        run: exit 1
  load-tests:
    runs-on: ubuntu-latest
    needs: deploy-nonprod
    steps:
      - name: Running load tests
        run: echo "Running load tests"
      - name: Failing tests
        if: ${{ !inputs.pass-unit-tests }}
        run: exit 1
  deploy-prod:
    runs-on: umbutu-latest
    needs: deploy-nonprod
    steps:
      - name: Deploy to prod
        run: echo "Deploying to prod"
