name: Update Badge

on:
  push:
    branches:
      - main

jobs:
  update-badge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update badge
        run: |
          # Your script to update the badge
          # Ensure this script modifies README.md
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          # Example modification to README.md
          echo "Updated badge status" >> README.md
          git add README.md
          git commit -m "Update status badge"

      - name: Push changes
        env:
          ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }}
        run: |
          if [ -z "${{ secrets.ACTIONS_PAT }}" ]; then
            echo "ACTIONS_PAT is not set. Make sure you have created a Personal Access Token with repo permissions and added it to the secrets."
            exit 1
          fi
          git remote set-url origin https://x-access-token:${ACTIONS_PAT}@github.com/${{ github.repository }}
          git push origin HEAD:main
