name: Update Badge

on:
 # push:
  repository_dispatch:
    types: [update_badge]

jobs:
  update-badge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update badge
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          # Replace the badge in ADRApproval.md
          sed -i 's|<img alt="Grey Tick" src="https://img.shields.io/badge/status-new-lightgrey">|<img alt="Green Tick" src="https://img.shields.io/badge/status-approved-brightgreen">|g' ADRApproval.md
          git add ADRApproval.md
          git commit -m "Update status badge to approved"
          git push origin HEAD:main

      - name: Push changes
        env:
          ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }}
        run: |
          if [ -z "${{ secrets.ACTIONS_PAT }}" ]; then
            echo "ACTIONS_PAT is not set. Make sure you have created a Personal Access Token with repo permissions and added it to the secrets."
            exit 1
          fi
          git remote set-url origin https://x-access-token:${ACTIONS_PAT}@github.com/${{ github.repository }}
          git push origin HEAD:main
