name: Update Badge
on:
  push:
  repository_dispatch:
    types: [update_badge]

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Update Badge in README.md
        run: |
          sed -i 's/status-badge-new/status-badge-voted/' README.md

      - name: Commit Changes
        run: |
          git config --global user.name "$(git log -1 --pretty=format:'%an')"
          git config --global user.email "$(git log -1 --pretty=format:'%ae')"
          git add README.md
          git commit -m 'Update status badge to voted'
          git push
