name: Update ADR Log
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-adr-log:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Use the desired Node.js version

      - name: Install adr-log globally
        run: npm install -g adr-log

      - name: Update ADR log
        run: |
          git config --global user.name "Carmen Lup"
          git config --global user.email "carmen.gabriela.lp@gmail.comm"
          adr-log -d ${{ github.workspace }}/adr -i ${{ github.workspace }}/index.md -e ${{ github.workspace }}/adr/template.md
          git add index.md
          git commit -m "Update ADR log"
          git push origin main
