name: Update Badge

on:
  push:
    branches:
      - main

jobs:
  update-badge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update badge
        run: |
          # Your script to update the badge
          # Ensure this script modifies ADRApproval.md
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          # Example modification to ADRApproval.md
          # find text "status: new" and replace with "status: voted" in ADRApproval.md
          # also chenge the badge to voted green color
          sed -i 's/status: new/status: voted/g' ADRApproval.md
          sed -i 's/red/green/g' ADRApproval.md
          # echo "Updated badge status" >> ADRApproval.md
          git add ADRApproval.md
          git commit -m "Update status badge"

      - name: Push changes
        env:
          ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }}
        run: |
          if [ -z "${{ secrets.ACTIONS_PAT }}" ]; then
            echo "ACTIONS_PAT is not set. Make sure you have created a Personal Access Token with repo permissions and added it to the secrets."
            exit 1
          fi
          git remote set-url origin https://x-access-token:${ACTIONS_PAT}@github.com/${{ github.repository }}
          git push origin HEAD:main
